version: '3.8'
services:
  test:
    container_name: "test"
    image: test:0.0.3
    networks:
      test_net:
        ipv4_address: 192.160.40.13
networks:
    test_net:
        driver: bridge
        name: test-public-net
        ipam:
            config:
                - subnet: 192.160.40.0/24
